name: Pluginus1
version: die einzig wahre
author: Meyssus und Lassus
main: wasdenn.Main

commands:
  back:
    description: Dahin wo du nach 5 Sekunden gewesen bist.
    usage: </command>

  ope:
    description: dann kommt BigMac und bannt dich weg, diggah.
    usage: </command>

  inv:
    description: Inventar wird gecleart/zurückgeholt
    usage: </command>

  gm:
    description: setzt dich in den spectator mode
    usage: </command>

  dersatzdesmeyssam:
    description: Meyssam hat immer Recht
    usage: </command>

  wahrheit:
    description: Zeigt die Wahrheit an
    usage: </wahrheit>

  heal:
    description: helth, ein gesunder Witz heilt dich :)
    usage: </heal>

  reset:
    description: Hi
    usage: </reset>

  wartung:
    description: Setzt den Server in den Wartungsmodus (und umgekehrt)
    usage: </wartung>