name: Pluginus1
version: π
api-version: 1.15
authors: [Meyssus, Lassus]
main: wasdenn.Main

commands:
  setpos:
    description: Speichert die Position unter dem Namen, den du ihr gibst.
    usage: </setpos>
  back:
    description: Dahin wo du nach 5 Sekunden gewesen bist.
    usage: </command>

  ope:
    description: dann kommt BigMac und bannt dich weg, diggah.
    usage: </command>

  inv:
    description: Inventar wird gecleart/zurückgeholt
    usage: </command>

  gm:
    description: setzt dich in den spectator mode
    usage: </command>

  dersatzdesmeyssam:
    description: Meyssam hat immer Recht
    usage: </command>

  wahrheit:
    description: Zeigt die Wahrheit an
    usage: </wahrheit>

  heal:
    description: helth, ein gesunder Witz heilt dich :)
    usage: </heal>

  gg:
    descripton: Die GunGame Commands
    usage: </gg>

  wartung:
    description: Setzt den Server in den Wartungsmodus (und umgekehrt)
    usage: </wartung>

